2020-07-15 16:33:31 ERROR [20010-Thread-6] log.log_response line 228: Internal Server Error: /teachers_data/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 152, in get_teachers_data
    print(key + ':' + value)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2020-07-15 16:33:31 ERROR [20010-Thread-6] basehttp.log_message line 124: "GET /teachers_data/ HTTP/1.1" 500 83287
2020-07-15 16:33:59 WARNING [20047-Thread-3] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-15 16:57:26 WARNING [20660-Thread-3] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-15 16:57:29 WARNING [20660-Thread-11] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-15 16:57:40 WARNING [20660-Thread-19] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-15 16:58:23 WARNING [20660-Thread-29] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-15 17:04:03 WARNING [20871-Thread-5] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 10:23:40 WARNING [6421-Thread-4] log.log_response line 228: Not Found: /favicon.ico
2020-07-16 10:23:40 WARNING [6421-Thread-4] basehttp.log_message line 124: "GET /favicon.ico HTTP/1.1" 404 12734
2020-07-16 10:38:12 WARNING [6421-Thread-72] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 10:48:04 ERROR [7244-Thread-2] log.log_response line 228: Internal Server Error: /subjects_show
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: subjects_show
2020-07-16 10:48:04 ERROR [7244-Thread-2] basehttp.log_message line 124: "GET /subjects_show HTTP/1.1" 500 97596
2020-07-16 10:48:36 ERROR [7274-Thread-3] log.log_response line 228: Internal Server Error: /subjects_show/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: subjects_show
2020-07-16 10:48:36 ERROR [7274-Thread-3] basehttp.log_message line 124: "GET /subjects_show/ HTTP/1.1" 500 97744
2020-07-16 10:48:53 WARNING [7293-Thread-3] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 10:56:16 WARNING [7293-Thread-17] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 10:56:52 WARNING [7293-Thread-21] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 10:58:37 WARNING [7293-Thread-23] basehttp.log_message line 124: "GET /static/html/teachers.html?sno=1 HTTP/1.1" 404 1684
2020-07-16 10:58:49 WARNING [7293-Thread-26] basehttp.log_message line 124: "GET /static/html/teachers.html?sno=1 HTTP/1.1" 404 1684
2020-07-16 11:00:04 WARNING [7293-Thread-30] basehttp.log_message line 124: "GET /static/images/hot-icon-small.png HTTP/1.1" 404 1699
2020-07-16 11:00:14 WARNING [7293-Thread-32] basehttp.log_message line 124: "GET /static/teachers.html?sno=1 HTTP/1.1" 404 1669
2020-07-16 11:18:12 WARNING [7293-Thread-37] log.log_response line 228: Not Found: /api/subjects_show/
2020-07-16 11:18:12 WARNING [7293-Thread-37] basehttp.log_message line 124: "GET /api/subjects_show/ HTTP/1.1" 404 12869
2020-07-16 11:20:45 WARNING [7293-Thread-44] basehttp.log_message line 124: "GET /static/html/teachers.html?sno=1 HTTP/1.1" 404 1684
2020-07-16 11:25:43 WARNING [7293-Thread-57] basehttp.log_message line 124: "GET /static/html/teachers.html?sno=1 HTTP/1.1" 404 1684
2020-07-16 13:49:27 ERROR [7293-Thread-91] log.log_response line 228: Internal Server Error: /subjects_show/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show.html',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].intro' from 'subjects[0].intro'
2020-07-16 13:49:27 ERROR [7293-Thread-91] basehttp.log_message line 124: "GET /subjects_show/ HTTP/1.1" 500 151959
2020-07-16 13:50:25 ERROR [7293-Thread-93] log.log_response line 228: Internal Server Error: /subjects_show/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show.html',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].intro' from 'subjects[0].intro'
2020-07-16 13:50:25 ERROR [7293-Thread-93] basehttp.log_message line 124: "GET /subjects_show/ HTTP/1.1" 500 151963
2020-07-16 13:55:48 ERROR [7293-Thread-101] log.log_response line 228: Internal Server Error: /subjects_show/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show.html',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].intro' from 'subjects[0].intro'
2020-07-16 13:55:48 ERROR [7293-Thread-101] basehttp.log_message line 124: "GET /subjects_show/ HTTP/1.1" 500 152057
2020-07-16 13:56:01 ERROR [7293-Thread-104] log.log_response line 228: Internal Server Error: /subjects_show/
Traceback (most recent call last):
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/scanv/PycharmProjects/django-day15/djangotest/polls/views.py", line 180, in subjects_show
    return render(request, 'subjects_show.html',)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/scanv/PycharmProjects/django-day15/venv/lib/python3.5/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].intro' from 'subjects[0].intro'
2020-07-16 13:56:01 ERROR [7293-Thread-104] basehttp.log_message line 124: "GET /subjects_show/ HTTP/1.1" 500 151821
2020-07-16 15:01:47 WARNING [16315-Thread-3] log.log_response line 228: Not Found: /favicon.ico
2020-07-16 15:01:47 WARNING [16315-Thread-3] basehttp.log_message line 124: "GET /favicon.ico HTTP/1.1" 404 12848
